<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>true</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisualStudio.CSharpNavigator.Roslyn\VisualStudio.CSharpNavigator.Roslyn.csproj" />
    <ProjectReference Include="..\VisualStudio.CSharpNavigator.Protocol\VisualStudio.CSharpNavigator.Protocol.csproj" />
    <ProjectReference Include="..\VisualStudio.CSharpNavigator.Abstractions\VisualStudio.CSharpNavigator.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
    <PackageReference Include="Microsoft.VisualStudio.LanguageServices" Version="4.14.0" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <VSIXSourceItem Include="$(OutputPath)Microsoft.Bcl.AsyncInterfaces.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.Buffers.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.IO.Pipelines.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.Memory.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.Runtime.CompilerServices.Unsafe.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.Text.Json.dll" />
    <VSIXSourceItem Include="$(OutputPath)System.Threading.Tasks.Extensions.dll" />
  </ItemGroup>

</Project>
